<h2 class="latest_shows"><a href="#">Latest Shows</a></h2>
<ul class="latest_shows_list">
    <li><a href="/japanese-drama/akumu-chan/">Akumu-Chan (Japan)</a></li>
    <li><a href="/korean-drama/can-we-get-married/">Can We Get Married (Korean)</a></li>
    <li><a href="/taiwanese-drama/die-sterntaler/">Die Sterntaler (Taiwan)</a></li>
    <li><a href="/japanese-drama/doctor-x/">Doctor X (Japan)</a></li>
    <li><a href="/korean-drama/five-fingers/">Five Fingers (Korean)</a></li>
    <li><a href="/korean-drama/full-house-2/">Full House 2 (Korean)</a></li>
    <li><a href="/japanese-drama/going-my-home/">Going My Home (Japan)</a></li>
    <li><a href="/japanese-drama/hana-no-zubora-meshi/">Hana no Zubora Meshi (Japan)</a></li>
    <li><a href="/japanese-drama/hitorishizuka/">Hitorishizuka (Japan)</a></li>
    <li><a href="/korean-drama/missing-you/">Missing You (Korean)</a></li>
    <li><a href="/japanese-drama/kodoku-no-gurume-2/">Kodoku no Gurume 2 (Japan)</a></li>
    <li><a href="/japanese-drama/koisuru-hae-onna/">Koisuru Hae Onna (Japan)</a></li>
    <li><a href="/japanese-drama/koukou-nyuushi/">Koukou Nyuushi (Japan)</a></li>
    <li><a href="/taiwanese-drama/love-now/">Love, Now (Taiwan)</a></li>
    <li><a href="/japanese-drama/makete-katsu/">Makete Katsu (Japan)</a></li>
    <li><a href="/korean-drama/may-queen/">May Queen (Korean)</a></li>
    <li><a href="/taiwanese-drama/miss-rose/">Miss Rose (Taiwan)</a></li>
    <li><a href="/japanese-drama/monsters/">MONSTERS (Japan)</a></li>
    <li><a href="/korean-drama/my-daughter-seo-young/">My Daughter SeoYoung (Korean)</a></li>
    <li><a href="/korean-drama/my-love-madame-butterfly/">My Love, Madame Butterfly (Korean)</a></li>
    <li><a href="/korean-drama/oohlala-spouses/">Oohlala Spouses (Korean)</a></li>
    <li><a href="/japanese-drama/ooku-arikoto-iemitsu-hen/">Ooku (Japan)</a></li>
    <li><a href="/japanese-drama/osozaki-no-himawari/">Osozkai no Himawari (Japan)</a></li>
    <li><a href="/japanese-drama/perfect-blue/">Perfect Blue (Japan)</a></li>
    <li><a href="/japanese-drama/priceless/">Priceless (Japan)</a></li>
    <li><a href="/korean-drama/rascal-sons/">Rascal Sons (Korean)</a></li>
    <li><a href="/japanese-drama/resident5-nin-no-kenshui/">Resident 5 Nin no Kenshui (Japan)</a></li>
    <li><a href="/japanese-drama/sousa-chizu-no-onna/">Sousa Chizu no Onna (Japan)</a></li>
    <li><a href="/japanese-drama/sugarless/">Sugarless (Japan)</a></li>
    <li><a href="/korean-drama/the-3rd-ward/">The 3rd Ward (Korean)</a></li>
    <li><a href="/korean-drama/the-great-seer/">The Great Seer (Korean)</a></li>
    <li><a href="/korean-drama/horse-doctor/">The Horse Doctor (Korean)</a></li>
    <li><a href="/korean-drama/the-great-kings-dream/">The Great Kings Dream (Korean)</a></li>
    <li><a href="/japanese-drama/tokyo-airport/">Tokyo Airport (Japan)</a></li>
    <li><a href="/japanese-drama/tokyo-zenryoku-shoujo/">Tokyo Zenryoku Shoujo (Japan)</a></li>
    <li><a href="/korean-drama/vampire-prosecutor-2/">Vampire Prosecutor 2 (Korean)</a></li>
    <li><a href="/korean-drama/what-is-mom/">What is Mom (Korean)</a></li>
    <li><a href="/japanese-drama/yuusha-yoshihiko-to-akuryo-no-kagi/">Yuusha Yoshihiko to Akuryo no Kagi (Japan)</a></li>
</ul>
